# Site settings
title: ZydiaLabs
email: hello@zydialabs.com
description: "ZydiaLabs homepage."
baseurl: ""
url: "http://zydialabs.com"
twitter_username: ZydiaLabs
github_username:  ZydiaLabs
paginate: 20

# Build settings
markdown: kramdown
permalink: /blog/p/:title
